ARSN-21 Upgrade Node to 16
scality/Arsenal pull request #1649
Opened 2021-12-07 13:36 UTC by dimitri-bourreau

This PR aims to upgrade Node from 10 to 16.

2021-12-07 13:36 UTC, bert-e commented
# Hello dimitri-bourreau,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/arsenal/bert-e/doc/user).





*Status report is not available.*

2021-12-07 13:36 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/7.10/improvement/ARSN-21-Upgrade-Node-to-16` with contents from `improvement/ARSN-21-Upgrade-Node-to-16`
and `development/7.10`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/7.10/improvement/ARSN-21-Upgrade-Node-to-16 origin/development/7.10
 $ git merge origin/improvement/ARSN-21-Upgrade-Node-to-16
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/7.10/improvement/ARSN-21-Upgrade-Node-to-16
```

2021-12-07 17:29 UTC, miniscruff approved these changes

2021-12-07 17:30 UTC, miniscruff requested changes
Should update the "engine" value in package.json as well

2022-01-11 22:19 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ARSN-21 contains:


* `7.10.6`

* `7.4.14`

* `8.1.18`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `7.10.6`

* `7.4.15`

* `8.1.19`


Please check the `Fix Version/s` of ARSN-21, or the target
branch of this pull request.

2022-01-11 22:21 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/7.10/improvement/ARSN-21-Upgrade-Node-to-16` with contents from `improvement/ARSN-21-Upgrade-Node-to-16`
and `development/7.10`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/7.10/improvement/ARSN-21-Upgrade-Node-to-16 origin/development/7.10
 $ git merge origin/improvement/ARSN-21-Upgrade-Node-to-16
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/7.10/improvement/ARSN-21-Upgrade-Node-to-16
```

2022-01-11 22:26 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/improvement/ARSN-21-Upgrade-Node-to-16` with contents from `w/7.10/improvement/ARSN-21-Upgrade-Node-to-16`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/improvement/ARSN-21-Upgrade-Node-to-16 origin/development/8.1
 $ git merge origin/w/7.10/improvement/ARSN-21-Upgrade-Node-to-16
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/improvement/ARSN-21-Upgrade-Node-to-16
```

2022-01-12 02:39 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/ARSN-21-Upgrade-Node-to-16` into
`development/7.4`
* [w/7.10/improvement/ARSN-21-Upgrade-Node-to-16](https://github.com/scality/arsenal/compare/development/7.10...w/7.10/improvement/ARSN-21-Upgrade-Node-to-16) will be merged into `development/7.10` (pull request #1662)
* [w/8.1/improvement/ARSN-21-Upgrade-Node-to-16](https://github.com/scality/arsenal/compare/development/8.1...w/8.1/improvement/ARSN-21-Upgrade-Node-to-16) will be merged into `development/8.1` (pull request #1663)



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.4.10`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2022-01-12 02:39 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @miniscruff

2022-01-19 09:56 UTC, dimitri-bourreau commented
@bert-e help

2022-01-19 09:56 UTC, bert-e commented
# Help page



The following options and commands are available at this time.

## Options ##


name   | description  | privileged   | authored
------ | ------------ | ------------ |----------
:arrow_right: **bypass_incompatible_branch** | Bypass the check on the source branch prefix |  :star:  | 
:arrow_right: **bypass_jira_check** | Bypass the Jira issue check |  :star:  | 
:arrow_right: **bypass_peer_approval** | Bypass the pull request peers' approval |  :star:  | 
:arrow_right: **wait** | Instruct Bert-E not to run until further notice. |  | 
:arrow_right: **bypass_commit_size** | Bypass the check on the size of the changeset ```TBA``` |  :star:  | 
:arrow_right: **create_pull_requests** | Allow the creation of integration pull requests. |  | 
:arrow_right: **unanimity** | Change review acceptance criteria from `one reviewer at least` to `all reviewers` |  | 
:arrow_right: **bypass_build_status** | Bypass the build and test status |  :star:  | 
:arrow_right: **bypass_leader_approval** | Bypass the pull request leaders' approval |  :star:  | 
:arrow_right: **bypass_author_approval** | Bypass the pull request author's approval |  :star:  | 
:arrow_right: **approve** | Instruct Bert-E that the author has approved the pull request. |  |  :writing_hand: 
:arrow_right: **after_pull_request** | Wait for the given pull request id to be merged before continuing with the current one. |  | 
:arrow_right: **no_octopus** | Prevent Wall-E from doing any octopus merge and use multiple consecutive merge instead |  | 



## Commands ##


name   | description  | privileged
------ | ------------ | ------------
:arrow_right: **clear** | Remove all comments from Bert-E from the history ```TBA``` | 
:arrow_right: **status** | Print Bert-E's current status in the pull request ```TBA``` | 
:arrow_right: **force_reset** | Delete integration branches & pull requests, and restart merge process from the beginning. | 
:arrow_right: **reset** | Try to remove integration branches unless there are commits on them which do not appear on the source branch. | 
:arrow_right: **retry** | Re-start a fresh build ```TBA``` | 
:arrow_right: **help** | Print Bert-E's manual in the pull request. | 
:arrow_right: **build** | Re-start a fresh build ```TBA``` |

2022-01-19 09:56 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ARSN-21 contains:


* `7.10.6`

* `7.4.15`

* `8.1.19`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `7.10.6`

* `7.4.16`

* `8.1.20`


Please check the `Fix Version/s` of ARSN-21, or the target
branch of this pull request.

2022-01-19 09:58 UTC, dimitri-bourreau commented
@bert-e approve

2022-01-19 09:59 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ARSN-21 contains:


* `7.10.6`

* `7.4.15`

* `8.1.19`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `7.10.6`

* `7.4.16`

* `8.1.20`


Please check the `Fix Version/s` of ARSN-21, or the target
branch of this pull request.




*The following options are set:* **approve**

2022-01-19 23:23 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @miniscruff







*The following options are set:* **approve**

2022-01-19 23:26 UTC, nicolas2bert approved these changes

2022-01-19 23:37 UTC, rahulreddy approved these changes

2022-01-19 23:58 UTC, jonathan-gramain approved these changes

2022-01-20 00:09 UTC, miniscruff approved these changes

2022-01-20 00:09 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/7.10`

* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.4.10`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-01-20 00:11 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/7.10`

* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/6.4`
* `stabilization/7.4.10`



Please check the status of the associated issue ARSN-21.

Goodbye dimitri-bourreau.

2022-01-20 00:11 UTC, merged