ARSN-328 Exclude keys based on their dataStoreName
scality/Arsenal pull request #2111
Opened 2023-04-10 13:04 UTC by nicolas2bert

To list the current versions using the **listLifecycleCurrents** function, the filtering is performed at the MongoDB query level.

In contrast, when listing the non-current versions with the **listLifecycleNoncurrents** function, filtering is done at the application level. Here, each key is evaluated and assessed for eligibility based on its datastore name. 

Finally, when calling the **listLifecycleOrphans** function to list the orphan delete markers, no filtering is done based on the datastore name. This is because orphan delete markers do not go through a transition workflow.

2023-04-10 13:04 UTC, bert-e commented
# Hello nicolas2bert,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://bert-e.scality.net/scality/arsenal/doc/user).





*Status report is not available.*

2023-04-10 13:04 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ARSN-328 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.1.93`


Please check the `Fix Version/s` of ARSN-328, or the target
branch of this pull request.

2023-04-10 13:05 UTC, nicolas2bert commented
ping

2023-04-10 13:05 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2023-04-13 22:07 UTC, jonathan-gramain requested changes

2023-04-13 22:07 UTC, jonathan-gramain commented on lib/algos/list/delimiterCurrent.ts
> +        this.excludedDataStoreName = parameters.excludedDataStoreName;
Should also update JSDoc with this param

2023-04-13 22:07 UTC, jonathan-gramain commented on lib/algos/list/delimiterNonCurrent.js
> +    _trimAndStringify(value, staleDate) {
```suggestion
    _trimAndStringify(parsedMD, staleDate) {
```

2023-04-13 22:07 UTC, jonathan-gramain commented on lib/algos/list/delimiterNonCurrent.js
> +            if (p.length >= TRIM_METADATA_MIN_BLOB_SIZE) {
This check wouldn't work anymore because p is now parsed metadata

2023-04-13 22:07 UTC, jonathan-gramain commented on lib/algos/list/delimiterNonCurrent.js
> +        // The following version is pushed only:
If I understand the code flow, it seems that we always have to parse the metadata in any case. I'd suggest to parse it at the beginning then, and use the fields directly thereafter, as it is now the tentative optimizations only seem to clutter the code.

2023-04-13 22:07 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ARSN-328 contains:


* `8.1.93`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.1.97`


Please check the `Fix Version/s` of ARSN-328, or the target
branch of this pull request.

2023-04-13 22:18 UTC, RachedBenMustapha approved these changes

2023-04-14 18:57 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @jonathan-gramain

2023-04-14 20:59 UTC, jonathan-gramain requested changes

2023-04-14 20:59 UTC, jonathan-gramain commented on lib/algos/list/delimiterOrphanDeleteMarker.js
> +            if (this.skipping.length >= TRIM_METADATA_MIN_BLOB_SIZE) {
```suggestion
            if (s.length >= TRIM_METADATA_MIN_BLOB_SIZE) {
```

2023-04-14 21:32 UTC, jonathan-gramain approved these changes

2023-04-14 21:32 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2023-04-14 21:42 UTC, rahulreddy commented
/bypass_author_approval

2023-04-14 21:50 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.10`
* `development/7.4`
* `development/7.70`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **bypass_author_approval**

2023-04-14 21:58 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.10`
* `development/7.4`
* `development/7.70`



Please check the status of the associated issue ARSN-328.

Goodbye nicolas2bert.

2023-04-14 21:58 UTC, merged