ARSN-336 Log KMS Result Message
scality/Arsenal pull request #2121
Opened 2023-05-22 08:48 UTC by scality-gelbart

fixes S3C-5516

2023-05-22 08:48 UTC, bert-e commented
# Hello scality-gelbart,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://bert-e.scality.net/scality/arsenal/doc/user).





*Status report is not available.*

2023-05-22 08:57 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2023-05-25 14:37 UTC, jonathan-gramain requested changes
The intent to help troubleshoot issues is valid, but I think we need to change how and what we dump info, keeping in mind the following:

- what is the rate of messages, is there a risk of overflowing logs with too much lines on busy systems
- what is the content of the logged messages, do we risk leaking in logs sensitive info like customer keys etc.
- `logger.error`: this will appear as an error log, should it be a debug log instead?
- on formatting: we should format the logs, for example: `log.info('something happened', { reason: "bleh", client: "some-client" })`, instead of `log.info(lots_of_things)` which might log unwanted things and/or confuse the reader of the logs
- target should be `development/7.x` (`7.10` or `7.70` for respectively RING 8 or RING 9), `development/8.x` will only appear in Artesca releases.

2023-05-25 14:37 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @jonathan-gramain

2023-05-25 19:18 UTC, scality-gelbart commented
> The intent to help troubleshoot issues is valid, but I think we need to change how and what we dump info, keeping in mind the following:
> 
>     * what is the rate of messages, is there a risk of overflowing logs with too much lines on busy systems
> 
>     * what is the content of the logged messages, do we risk leaking in logs sensitive info like customer keys etc.
> 
>     * `logger.error`: this will appear as an error log, should it be a debug log instead?
> 
>     * we should format the logs, for example: `log.info('something happened', { reason: "bleh", client: "some-client" })`, instead of `log.info(lots_of_things)` which might log unwanted things and/or confuse the reader of the logs
> 
>     * target should be `development/7.x` (`7.10` or `7.70` for respectively RING 8 or RING 9), `development/8.x` will only appear in Artesca releases.

thx for your reply @jonathan-gramain, I realize this ticket is way beyond my very basic dev skills so I'll stop trying... for now

2023-05-25 19:18 UTC, closed without merging