ft: ZENKO-433 add item count support incremental update and refresh
scality/Arsenal pull request #497
Opened 2018-05-31 20:27 UTC by alexanderchan-scality

2018-05-31 23:00 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-05-31 23:56 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-01 00:41 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-05 17:42 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-05 17:54 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-05 18:32 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-05 19:11 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-05 20:44 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-05 23:06 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-06 03:00 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-06 03:20 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-06 17:01 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-06 17:03 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-06 17:21 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-06 19:14 UTC, rachedbenmustapha requested changes

2018-06-06 19:14 UTC, rachedbenmustapha commented on lib/storage/metadata/mongoclient/MongoClientInterface.js
> +            mongoCall.op = this.putObjectVerCase1.bind(this);
We should avoid binding functions in the per-request code path, as it puts extra pressure on the GC that can be detrimental under high load.

2018-06-06 19:14 UTC, RachedBenMustapha commented on lib/storage/metadata/mongoclient/MongoClientInterface.js
> +        return dataCounterHelper.addObjWrapper(
This inverts control, even if it's a bit more repetitive the following pattern:

- do operation
- if no error, then account for it

would be more readable and would avoid conditioning the mongo call to the wrapper not failing. Also it incurs a lot of arguments serialization that can be a performance penalty.

2018-06-06 20:59 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-06 23:26 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-07 00:04 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-07 01:30 UTC, alexanderchan-scality commented
closing in favor of #499

2018-06-07 01:30 UTC, closed without merging