Feature/zenko 18/metadata proxy server
scality/Arsenal pull request #498
Opened 2018-06-06 23:35 UTC by ploki

replaces #462

2018-06-06 23:35 UTC, bert-e commented
# Hello ploki,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-06-06 23:35 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers

2018-06-06 23:38 UTC, rahulreddy commented
@bert-e wait

2018-06-08 21:57 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-08 22:15 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-08 22:29 UTC, vrancurel submitted a review, later dismissed

2018-06-08 23:58 UTC, philipyoo submitted a review, later dismissed

2018-06-09 00:26 UTC, alexanderchan-scality submitted a review, later dismissed

2018-06-11 22:25 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-11 23:13 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-12 17:54 UTC, ssalaues submitted a review, later dismissed

2018-06-12 22:27 UTC, rahulreddy requested changes
I like your usage of `RequestDispatcher` in the tests.

2018-06-12 22:27 UTC, rahulreddy commented on lib/storage/metadata/proxy/BucketdRoutes.js
> +            bucketName, objectName, JSON.parse(objectValue),
`JSON.parse` will call cause a server crash if the JSON is malformed. I recommend a `try...catch` for safe parsing.

2018-06-12 22:27 UTC, rahulreddy commented on lib/storage/metadata/proxy/BucketdRoutes.js
> +    _destringifyValues(data) {
Is this method being used anywhere or is it a placeholder for future use?

2018-06-12 22:27 UTC, rahulreddy commented on lib/storage/metadata/proxy/BucketdRoutes.js
> +            const value = JSON.parse(entry.value);
I recommend safe json parsing as above.

2018-06-12 22:27 UTC, rahulreddy commented on lib/storage/metadata/proxy/BucketdRoutes.js
> +     * @param {object} uriComponents -
You can list here the properties expected to be used in the object.

2018-06-12 22:27 UTC, rahulreddy commented on lib/storage/metadata/proxy/utils.js
> + * @return {string} ret.namespace
Can you add a one-liner describing what namespace and context are?

2018-06-12 22:27 UTC, rahulreddy commented on lib/storage/metadata/proxy/utils.js
> +        if (typeIndex === -1 || typeIndex === pathname.length - 1) {
Suggestion: If you abstract `pathname.length - 1` into a var, it will be more readable.

2018-06-12 22:27 UTC, rahulreddy commented on lib/storage/metadata/proxy/utils.js
> +                     { uri, error: ex, errorStack: ex.stack });
`ex.message` is worth logging too.

2018-06-12 22:27 UTC, rahulreddy commented on lib/storage/metadata/proxy/utils.js
> +    }).on('error', cb).on('end', () => {
`http.IncomingMessage` emits `close` if the client abruptly disconnects. We need to add a listener and destroy the stream/cleanup when the `close` event is emitted. This was the source of our TCP socket leak issue in January.

2018-06-12 22:27 UTC, rahulreddy commented on tests/functional/metadataProxy/routesToMem.js
> +        ], err => done(err));
Minor style comment: In instances like this `err => done(err)` you can pass the callback directly `done`.

2018-06-13 00:34 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-13 00:36 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-13 00:41 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-13 01:06 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-13 06:35 UTC, rahulreddy submitted a review, later dismissed

2018-06-13 17:06 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-13 20:37 UTC, rahulreddy approved these changes

2018-06-13 20:46 UTC, ssalaues approved these changes

2018-06-13 20:47 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-06-13 20:47 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.0`




Please check the status of the associated issue ZENKO-18.

Goodbye ploki.

2018-06-13 20:47 UTC, merged