feature: ZENKO-483 Monitor CRR upload
scality/Arsenal pull request #528
Opened 2018-07-02 17:58 UTC by bennettbuchanan

See feature docs here: https://github.com/scality/backbeat/pull/356

2018-07-02 17:58 UTC, bert-e commented
# Hello bennettbuchanan,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-07-02 17:58 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers

2018-07-02 23:00 UTC, bennettbuchanan commented
@bert-e wait

2018-07-03 00:13 UTC, jonathan-gramain requested changes
Commented to add the error message in the log, the rest for me can wait a future refactor.

2018-07-03 00:13 UTC, jonathan-gramain commented on lib/backbeat/Metrics.js
> +            if (err && err.type) {
I'm not convinced this code is really useful (I think it's there to create a new instance of an arsenal error returned by `_getData`) and if so, probably not the right place or the right way to do this duplication. In doubt we can keep this, but we should consider reworking error handling in the module later on.

2018-07-03 00:13 UTC, jonathan-gramain commented on lib/backbeat/Metrics.js
> +                    method: 'Metrics.getObjectThroughput',
Let's log the error message with `error: err.message`

2018-07-03 00:13 UTC, jonathan-gramain commented on lib/backbeat/Metrics.js
> +            const timeSinceStart = (now - this._internalStart) / 1000;
I have seen this touchy computation code copied in multiple functions, as I commented in a previous PR it should be feasible to put it into a helper function or in some other file as a library function, so it can be tested independently and be confident it works ok across the various stats gathering functions. Ok to skip for now and keep for later.

2018-07-03 00:13 UTC, jonathan-gramain commented on lib/backbeat/Metrics.js
> +            let percentage = bytesComplete / totalBytesToComplete;
May be better to check if `totalBytesToComplete === 0` than relying on `isNaN`, though not sure this case can actually happen there.

Also could be clearer with a separate var `const ratio = ...`, then `const percentage = ...` below.

2018-07-03 20:56 UTC, bennettbuchanan commented on lib/backbeat/Metrics.js
> +            if (err && err.type) {
Okay, I see your concern though since this is the common error handling pattern for all the methods Metrics.js, I'll leave as-is for now.

2018-07-03 21:10 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-07-03 21:36 UTC, jonathan-gramain submitted a review, later dismissed

2018-07-03 21:56 UTC, tmacro submitted a review, later dismissed

2018-07-04 00:41 UTC, nicolas2bert submitted a review, later dismissed

2018-07-04 00:41 UTC, nicolas2bert commented on lib/backbeat/Metrics.js
> +     * @param {string} objectKey - the object key
`the object key name`?

2018-07-05 17:52 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-07-05 17:52 UTC, bennettbuchanan commented on lib/backbeat/Metrics.js
> +     * @param {string} objectKey - the object key
Updated! 😸

2018-07-05 18:31 UTC, nicolas2bert approved these changes

2018-07-05 18:32 UTC, jonathan-gramain approved these changes

2018-07-05 18:32 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.0`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-07-05 18:32 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.0`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`



Please check the status of the associated issue ZENKO-483.

Goodbye bennettbuchanan.

2018-07-05 18:32 UTC, merged