bf: ZENKO-751 tempfix set max object key limit
scality/Arsenal pull request #542
Opened 2018-07-26 00:02 UTC by philipyoo

Max key length will be set to 914 to account for different
situations. Default AWS key length is 1024, but mongo keys
allow for length of up to 1011. Factoring in version id,
and bucket match false (bucket name prefix), for now,
we will limit the key length to 914 and return an error
right away if object key length exceeds this limit.

2018-07-26 00:02 UTC, bert-e commented
# Hello philipyoo,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-07-26 00:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @RachedBenMustapha

* @bennettbuchanan

2018-07-26 00:30 UTC, dora-korpar approved these changes

2018-07-26 00:50 UTC, bennettbuchanan reviewed
💯While this does not meet AWS compatibility of a 1024 byte key length, it sounds like it's the best and safest option considering our time constraints?

2018-07-26 00:50 UTC, bennettbuchanan commented on lib/s3routes/routesUtils.js
> +        if (objectKey.length > OBJECT_KEY_LIMIT) {
I think we also need to factor in UTF-8 characters here. For example the character `僷` is a length of 1 but byte size of 3, which could result in us still exceeding the limit.

2018-07-26 00:50 UTC, bennettbuchanan commented on lib/s3routes/routesUtils.js
> +// - Mongo key limit of 1012
May be worth specifying that this limit is a byte limit of the string rather than a character length limit, unless I'm mistaken about this.

2018-07-26 00:50 UTC, bennettbuchanan commented on tests/unit/s3routes/routesUtils/isValidObjectKey.js
> +    });
Could be useful to add add a UTF-8 character unit test case that meets the key limit after the bucket prefix is applied (when using a max-length bucket name).

2018-07-26 00:51 UTC, bennettbuchanan commented
Thanks for handling this! 😸

2018-07-27 20:58 UTC, rahulreddy requested changes

2018-07-27 20:58 UTC, rahulreddy commented on lib/s3routes/routes.js
> +const OBJECT_KEY_BYTE_LIMIT = 915;
Please move this to `constants.js`. I will help us customize these values easily rather than hunting them down in files.

2018-07-27 20:58 UTC, rahulreddy commented on lib/s3routes/routes.js
> +                `key must not start with "${result.invalidPrefix}".`);
Can you adjust the message to `Invalid prefix - object key cannot start with "${result.invalidPrefix}".`

2018-07-27 20:58 UTC, rahulreddy commented on lib/s3routes/routes.js
> +            return errors.KeyTooLong.customizeDescription('Your key is ' +
`Object key is too long. Maximum number of bytes allowed in keys is ${OBJECT_KEY_BYTE_LIMIT}.`

2018-07-27 20:58 UTC, rahulreddy commented on lib/s3routes/routesUtils.js
> +// Setting a lower object key limit to account for:
Documenting this in constants.js is better.

2018-07-27 21:24 UTC, rahulreddy commented on tests/unit/s3routes/routesUtils/isValidObjectKey.js
> +const keyutf8 = '%EA%9D%8B崰㈌㒈保轖䳷䀰⺩ቆ楪秲ⴝ㿅鼎ꓜ퇬枅࿷염곞召㸾⌙ꪊᆐ庍뉆䌗幐鸆䛃➟녩ˍ뙪臅⠙≼绒벊냂詴 끴鹲萯⇂㭢䈊퉉楝舳㷖족痴䧫㾵᏷ำꎆ꼵껪멷㄀誕㳓腜쒃컹㑻鳃삚舿췈孨੦⮀Ǌ곓⵪꺼꜈嗼뫘悕錸瑺⁤륒㜓垻ㆩꝿ詀펉ᆙ舑䜾힑藪碙ꀎꂰ췊Ᏻ  㘺幽醛잯ද汧Ꟑꛒⶨ쪸숞헹㭔ꡔᘼ뺓ᡆ᡾ᑟ䅅퀭耓弧⢠⇙폪ް蛧⃪Ἔ돫ꕢ븥ヲ캂䝄쟐颺ᓾ둾Ұ껗礞ᾰ瘹蒯硳풛瞋襎奺熝妒컚쉴⿂㽝㝳駵鈚䄖戭䌸᫲ᇁ䙪
One last thing, can you break the lines for line limit?

2018-07-30 17:16 UTC, rahulreddy approved these changes

2018-07-30 17:17 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.0`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-07-30 17:21 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.0`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`



Please check the status of the associated issue ZENKO-751.

Goodbye philipyoo.

2018-07-30 17:21 UTC, merged

2018-07-30 17:22 UTC, bennettbuchanan commented
🍾