bf: ZENKO-903 retrieve new bucket list on report
scality/Arsenal pull request #547
Opened 2018-08-03 22:44 UTC by alexanderchan-scality

2018-08-03 22:44 UTC, bert-e commented
# Hello alexanderchan-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-08-03 22:44 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @RachedBenMustapha

* @bennettbuchanan

2018-08-06 17:26 UTC, anurag4DSB approved these changes

2018-08-06 17:26 UTC, anurag4DSB approved these changes

2018-08-06 17:28 UTC, alexanderchan-scality commented
@bert-e  wait

2018-08-06 19:33 UTC, JianqinWang approved these changes

2018-08-06 19:45 UTC, rahulreddy requested changes

2018-08-06 19:45 UTC, rahulreddy commented on lib/storage/metadata/mongoclient/MongoClientInterface.js
> +                    cachedRes.buckest = res.buckets;
`buckets` is misspelt as `buckest`

2018-08-06 20:02 UTC, bennettbuchanan approved these changes

2018-08-06 20:02 UTC, bennettbuchanan commented on lib/storage/metadata/mongoclient/MongoClientInterface.js
> +                    cachedRes.bucketList = [...res.bucketList];
Minor: Is the spread operator necessary?

2018-08-06 20:04 UTC, alexanderchan-scality commented on lib/storage/metadata/mongoclient/MongoClientInterface.js
> +                    cachedRes.bucketList = [...res.bucketList];
Looking at the code, at that point, there won't be any modification of the `res` object, so the creation of a new object with spread is not necessary. Will fix.

2018-08-07 00:21 UTC, rahulreddy approved these changes

2018-08-07 00:21 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.0`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-08-07 00:21 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.0`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`



Please check the status of the associated issue ZENKO-903.

Goodbye alexanderchan-scality.

2018-08-07 00:21 UTC, merged