fx: ZENKO-1112 Incomplete management client error logging
scality/Arsenal pull request #558
Opened 2018-09-05 20:35 UTC by nicolas2bert

2018-09-05 20:35 UTC, bert-e commented
# Hello nicolas2bert,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-09-05 20:35 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @RachedBenMustapha

* @bennettbuchanan

2018-09-06 23:01 UTC, rachedbenmustapha requested changes

2018-09-06 23:01 UTC, RachedBenMustapha commented on lib/errorUtils.js
> +        code: error.code,
From the docs, some attributes that can be useful to capture are also `stack` and `name`.

2018-09-10 18:31 UTC, tmacro approved these changes

2018-09-10 18:34 UTC, rachedbenmustapha approved these changes

2018-09-10 18:34 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.0`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-09-10 18:34 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.0`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`



Please check the status of the associated issue ZENKO-1112.

Goodbye nicolas2bert.

2018-09-10 18:34 UTC, merged