feat: fsDataFile service
scality/Arsenal pull request #598
Opened 2018-11-01 20:41 UTC by giacomoguiulfo

This PR adds the `fsDataFile` which is used for the implementation of the `fs-data` daemon.

2018-11-01 20:41 UTC, bert-e commented
# Hello giacomoguiulfo,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-11-01 20:41 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @RachedBenMustapha

* @rahulreddy

* @bennettbuchanan

2018-11-01 20:41 UTC, giacomoguiulfo commented
@bert-e wait

2018-11-01 22:48 UTC, alexanderchan-scality approved these changes
lgtm

2018-11-02 13:33 UTC, rachedbenmustapha requested changes
The existing `/DataFile` implementation also being filesystem-based, the naming is confusing as to what's the difference between to 2. Something that is actually different and sets the 2 implementations apart is that the new one uses passthrough paths while the other one uses hashing.

This implementation could be named `passhroughFile` and the flag `isPassthrough` and so on. Or at least something different than `fs`.

Also most of the `yarn.lock` changes seem gratuitous, were they intended for this PR?

2018-11-02 13:33 UTC, RachedBenMustapha commented on lib/network/rest/utils.js
> +            key: path.slice(12),
Why 12? A constant that is computed from the prefix length would be clearer

2018-11-02 13:33 UTC, RachedBenMustapha commented on lib/storage/data/file/DataFileStore.js
> +            return '';
Checks would be welcome in the callers so that they can fail with an "invalid argument"-type error instead of failing with an `ENOENT` error that would not immediately make sense to someone trying to understand in good faith (and not trying to exploit) why it's failing.

2018-11-02 22:02 UTC, giacomoguiulfo commented
Thanks for the review @RachedBenMustapha. I just addressed all the things you mentioned.

2018-11-02 22:21 UTC, rachedbenmustapha approved these changes
LGTM now :) Ideally my naming comment also applies to the cloudserver PR, although I can’t review it right now

2018-11-03 00:18 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `development/8.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.

2018-11-03 00:18 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`
* `development/8.0`



Please check the status of the associated issue ZENKO-1270.

Goodbye giacomoguiulfo.

2018-11-03 00:19 UTC, merged