ft: ZENKO-1240 ingestion bucket search in mongo
scality/Arsenal pull request #601
Opened 2018-11-08 23:55 UTC by philipyoo

Add the ability to find ingestion buckets directly from mongo.

2018-11-08 23:55 UTC, bert-e commented
# Hello philipyoo,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-11-08 23:55 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @RachedBenMustapha

* @rahulreddy

* @bennettbuchanan

2018-11-08 23:56 UTC, philipyoo commented
@bert-e wait

2018-11-09 00:25 UTC, JianqinWang commented on lib/storage/metadata/mongoclient/MongoClientInterface.js
> +            'value.ingestion': true,
right now there are 3 possible values for ingestion: `{ Status: 'Enabled' }`, `{ Status: 'Disabled' }`, `null`

2018-11-09 00:32 UTC, rahulreddy requested changes
I would not recommend leaking application logic into abstractions. They have to independent. What you can do is you can extend `MongoClientInterface` in Backbeat directly and write your own method there.

2018-11-09 00:43 UTC, philipyoo commented on lib/storage/metadata/mongoclient/MongoClientInterface.js
> +            'value.ingestion': true,
this arg is to indicate the return value should include the BucketInfo `ingestion` field, so unless the value is null, it should return the bucket

2018-11-09 00:46 UTC, philipyoo commented
@rahulreddy sounds good, closing and will implement an extension in backbeat

2018-11-09 00:46 UTC, closed without merging

2018-11-09 00:51 UTC, JianqinWang commented on lib/storage/metadata/mongoclient/MongoClientInterface.js
> +            'value.ingestion': true,
my bad, misread