feat(DataFileStore): add passthrough delete functionality
scality/Arsenal pull request #609
Opened 2018-11-27 21:27 UTC by giacomoguiulfo

This adds support to delete files when using the Passthrough DataFileStore. It also allows for configuring ReadOnly mode.

2018-11-27 21:27 UTC, bert-e commented
# Hello giacomoguiulfo,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-11-27 21:27 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @bennettbuchanan

* @rachedbenmustapha

* @rahulreddy

2018-11-27 21:46 UTC, vrancurel requested changes
Can you honor the readOnly flag for write too, event though we don't support writes. But at least s3-data users can benefit from this new flag.

2018-11-27 22:18 UTC, giacomoguiulfo commented
@vrancurel Done 👍

2018-12-07 22:04 UTC, alexanderchan-scality approved these changes

2018-12-07 22:10 UTC, tmacro approved these changes

2018-12-07 22:14 UTC, bennettbuchanan approved these changes

2018-12-07 22:47 UTC, philipyoo approved these changes

2018-12-07 22:48 UTC, vrancurel approved these changes

2018-12-07 22:49 UTC, giacomoguiulfo commented
@bert-e approve

2018-12-07 22:49 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `development/8.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2018-12-07 22:51 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`
* `development/8.0`



Please check the status of the associated issue ZENKO-1351.

Goodbye giacomoguiulfo.

2018-12-07 22:51 UTC, merged