ft: ZENKO-1560 add getter for metadata client
scality/Arsenal pull request #755
Opened 2019-03-08 19:43 UTC by philipyoo

Add a public method to get the metadata client from
metadata wrapper class.

2019-03-08 19:43 UTC, bert-e commented
# Hello philipyoo,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/arsenal/bert-e/doc/user).





*Status report is not available.*

2019-03-08 19:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @rahulreddy

* @bennettbuchanan

2019-03-11 18:21 UTC, alexanderchan-scality approved these changes

2019-03-11 18:43 UTC, JianqinWang approved these changes

2019-03-11 19:08 UTC, rahulreddy commented on lib/storage/metadata/MetadataWrapper.js
> +
I would rather have the method you intended to use here than exporting the client. It defeats the purpose of having a wrapper.

2019-03-11 19:08 UTC, rahulreddy requested changes
I would rather have the method you intended to use here than exporting the client. It defeats the purpose of having a wrapper.

2019-03-11 19:08 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @rahulreddy

* @bennettbuchanan





The following reviewers are expecting changes from the author, or must review again:

* @rahulreddy

2019-03-11 19:18 UTC, philipyoo commented
@rahulreddy 
The method is very specific to only ingestion within backbeat and the MetadataWrapper can create different internal clients. I don't think it would fit well on the wrapper either

The alternative was to have a second mongodb instance within backbeats lib/management; one that continues to use the existing MetadataWrapper, and the other that extends the MongoClientInterface (like how we were using it before). Basically 2 separate connections to the same mongo db

2019-03-11 23:17 UTC, rahulreddy approved these changes

2019-03-11 23:17 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @rahulreddy

* @bennettbuchanan

2019-03-12 18:11 UTC, philipyoo commented
@bert-e approve

2019-03-12 18:11 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `development/7.5`
* `development/8.0`
* `stabilization/7.4.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-03-12 18:13 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`
* `development/7.5`
* `development/8.0`
* `stabilization/7.4.3`



Please check the status of the associated issue ZENKO-1560.

Goodbye philipyoo.

2019-03-12 18:13 UTC, merged