feature: S3C-2785 add object lock check
scality/Arsenal pull request #992
Opened 2020-04-24 17:33 UTC by ilkescality

Adds objectLockEnabled check to Bucket info model.

Related: https://github.com/scality/cloudserver/pull/2508

2020-04-24 17:33 UTC, bert-e commented
# Hello ilkescality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/arsenal/bert-e/doc/user).





*Status report is not available.*

2020-04-24 17:33 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel` with contents from `feature/S3C-2785_ObjectLockCheckToBucketInfoModel`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel origin/development/8.1
 $ git merge origin/feature/S3C-2785_ObjectLockCheckToBucketInfoModel
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel
```

2020-04-24 18:33 UTC, tmacro approved these changes

2020-04-24 18:39 UTC, tmacro requested changes
I believe that the model version needs to be bumped here
https://github.com/scality/Arsenal/blob/development/8.1/lib/constants.js

2020-04-24 18:43 UTC, nicolas2bert approved these changes

2020-05-04 22:43 UTC, dora-korpar commented on tests/unit/models/BucketInfo.js
> +                assert.strictEqual(typeof dummyBucket.isObjectLockEnabled(),
Just wanna make sure this is what you meant for the test -> I'm pretty sure `objectLockEnabled` is defaulting to false, which will still allow the test to pass, but if you want to have it set to true, you have to set in in the instantiation for BucketInfo on line 149 :)

2020-05-04 22:51 UTC, dora-korpar commented
@tmacro I'm bumping the model version in my arsenal PR, and will update the readme in cloudserver as well

2020-05-04 23:41 UTC, dora-korpar approved these changes

2020-05-04 23:42 UTC, ilkescality commented
/approve

2020-05-04 23:42 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel` with contents from `feature/S3C-2785_ObjectLockCheckToBucketInfoModel`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel origin/development/8.1
 $ git merge origin/feature/S3C-2785_ObjectLockCheckToBucketInfoModel
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel
```





*The following options are set:* **approve**

2020-05-04 23:52 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/S3C-2785_ObjectLockCheckToBucketInfoModel` into
`development/7.7`
* [w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel](https://github.com/scality/arsenal/compare/development/8.1...w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel) will be merged into `development/8.1` (pull request #997)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `stabilization/7.4.6`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.







*The following options are set:* **approve**

2020-05-04 23:52 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @rachedbenmustapha





The following reviewers are expecting changes from the author, or must review again:

* @tmacro







*The following options are set:* **approve**

2020-05-05 00:09 UTC, tmacro approved these changes

2020-05-05 00:09 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @rachedbenmustapha










*The following options are set:* **approve**

2020-05-05 01:05 UTC, rahulreddy requested changes
@ilkescality Can you please add another test that shows that a bucket created has object lock disabled as default?

2020-05-05 01:05 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @rachedbenmustapha





The following reviewers are expecting changes from the author, or must review again:

* @rahulreddy







*The following options are set:* **approve**

2020-05-05 01:27 UTC, bert-e commented
# History mismatch



Merge commit #b0734bff1c8348038bf6954c6ca6f4667ba76917 on the integration branch
`w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel` is merging a branch which is neither the current
branch `feature/S3C-2785_ObjectLockCheckToBucketInfoModel` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `feature/S3C-2785_ObjectLockCheckToBucketInfoModel` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2020-05-05 01:29 UTC, ilkescality commented
@bert-e force-reset

2020-05-05 01:29 UTC, bert-e commented
# Unknown command



I didn't understand this comment by @ilkescality:

> @bert-e force-reset

I don't know what `force` means.

Please **edit** or **delete** the corresponding comment so I can move on.




*The following options are set:* **approve**

2020-05-05 01:29 UTC, ilkescality commented
@bert-e reset

2020-05-05 01:29 UTC, bert-e commented
# Unknown command



I didn't understand this comment by @ilkescality:

> @bert-e force-reset

I don't know what `force` means.

Please **edit** or **delete** the corresponding comment so I can move on.




*The following options are set:* **approve**

2020-05-05 01:30 UTC, bert-e commented
# Unknown command



I didn't understand this comment by @ilkescality:

> @bert-e force-reset

I don't know what `force` means.

Please **edit** or **delete** the corresponding comment so I can move on.




*The following options are set:* **approve**

2020-05-05 01:30 UTC, bert-e commented
# History mismatch



Merge commit #b0734bff1c8348038bf6954c6ca6f4667ba76917 on the integration branch
`w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel` is merging a branch which is neither the current
branch `feature/S3C-2785_ObjectLockCheckToBucketInfoModel` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `feature/S3C-2785_ObjectLockCheckToBucketInfoModel` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2020-05-05 01:30 UTC, ilkescality commented
@bert-e reset

2020-05-05 01:31 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2020-05-05 01:31 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel` with contents from `feature/S3C-2785_ObjectLockCheckToBucketInfoModel`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel origin/development/8.1
 $ git merge origin/feature/S3C-2785_ObjectLockCheckToBucketInfoModel
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel
```





*The following options are set:* **approve**

2020-05-05 01:37 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/S3C-2785_ObjectLockCheckToBucketInfoModel` into
`development/7.7`
* [w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel](https://github.com/scality/arsenal/compare/development/8.1...w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel) will be merged into `development/8.1` (pull request #998)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `stabilization/7.4.6`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.







*The following options are set:* **approve**

2020-05-05 01:37 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @rachedbenmustapha





The following reviewers are expecting changes from the author, or must review again:

* @rahulreddy







*The following options are set:* **approve**

2020-05-05 02:06 UTC, rahulreddy approved these changes

2020-05-05 02:06 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/Arsenal/commit/93fe6fa94d853e78280651878d3d0ee512b61bdc) did not succeed in branch w/8.1/feature/S3C-2785_ObjectLockCheckToBucketInfoModel.




*The following options are set:* **approve**

2020-05-05 04:11 UTC, rahulreddy commented
@ilkescality  On 8.1 branch looks like you resolved the conflict in a way that `bucketPolicy` appears twice. Your forward port will pass if you fix that.

2020-05-05 04:35 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.7`

* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `stabilization/7.4.6`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2020-05-05 04:35 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.7`

* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`
* `stabilization/7.4.6`



Please check the status of the associated issue S3C-2785.

Goodbye ilkescality.

2020-05-05 04:35 UTC, merged

2020-05-05 04:42 UTC, ilkescality commented
> @ilkescality On 8.1 branch looks like you resolved the conflict in a way that `bucketPolicy` appears twice. Your forward port will pass if you fix that.

@rahulreddy Thanks for bringing this to my attention; I didn't get bert-e email for failed CI due to `Argument name clash` and didn't realize it until seeing this message and checking `eve` manually, it's fixed & merged now.